export interface User {
    id?: number,
    hubSpotPortalId?: number | null,
    firstName: string,
    lastName: string,
    emailAddress: string,
    domain?: string | null,
    password: string,
    secret: string,
    roles: string[],
    activationToken: string,
    isActive: boolean,
    companyInfoUserName?: string | null,
    companyInfoPassword?: string | null,
}
